Repository PandasWhoCode/version2, pull requests merged in 2025-05, with the labels that each got.

#22 ci: add workflow to validate conventional commits
  .github/workflows/validate-conventional-commits.yaml
  .gitignore
  images/.DS_Store
Labels: build, ci

#23 feat: Add initial python script
  src/v2query.py
Labels: feature, feat

#26 docs: fix README icon reference location
  README.md
Labels: bug, docs

#29 chore: remove .DS_Store file
  images/favicon_io/.DS_Store
Labels: bug, chore

#33 chore: Updated template to account for real JSON Attributes
  commons/static_site_generator.py
  templates/kaban_board.html
Labels: enhancement, chore

#35 feat: implementation for CLI
  .editorconfig
  .gitignore
  src/version_two_config.py
  version_two.py
Labels: feat

#31 ci: add dependabot and security files
  .github/SECURITY.md
  .github/dependabot.yml
Labels: ci

#38 docs: create the social preview file
  images/SocialPreview.png
Labels: docs

#41 fix: update name and directory for python files
  src/version2config.py
  version2.py
Labels: fix

#39 chore: Update version2query.py to use methods
  src/v2query.py
  src/version2query.py
Labels: feature, chore

#15 chore: Added config python module
  requirements.txt
  src/static_site_generator.py
  src/version2config.py
  version2.py
Labels: chore

#42 docs: add a readme for the current implemented CLI documentation
  current-implemented-CLI.md
Labels: docs

#43 docs: update readme to show setting gh token permissions
  README.md
Labels: docs

#46 feat: Refactor to include as a version2query class
  src/version2query.py
Labels: feat

#49 feat: MVP complete -- Update filters to include teams and generate the site with real data
  current-implemented-CLI.md
  src/static_site_generator.py
  src/version2config.py
  version2.py
Labels: feature, feat

#53 chore: update the order of CLI args and documentation
  current-implemented-CLI.md
  src/version2config.py
Labels: chore

#45 feat: Added github JSON loader and Fixed JS Search
  src/static_site_generator.py
  templates/kaban_board.html
  version2.py
Labels: feat

#62 feat: Added horizontal scrolling
  templates/kaban_board.html
Labels: enhancement, feat

#63 docs: update the readme with more details
  README.md
Labels: docs

#68 fix: All attributes part of search functionality
  .gitignore
  templates/kaban_board.html
Labels: fix

#70 docs: readme update team must be member of project board
  README.md
Labels: docs

#60 docs: Included mermaid diagram for readme.md
  README.md
Labels: chore

#72 docs: update README.md setup order
  README.md
Labels: docs

#75 fix(bug): fix printout by importing rich print
  src/queryFilter.py
Labels: bug, fix

#78 feat: Rename include/exclude teams to include/exclude projects
  README.md
  current-implemented-CLI.md
  src/queryFilter.py
  src/version2config.py
  src/version2query.py
  version2.py
Labels: feature, feat

#79 fix(bug): Too much reliance on teams still
  src/static_site_generator.py
  src/version2query.py
  templates/kaban_board.html
  version2.py
Labels: bug, fix

#81 feat: Make static_site_generator.py a standalone script
  src/static_site_generator.py
Labels: feature, feat

#83 fix(bug): Update tasks to always have status
  src/static_site_generator.py
Labels: bug, fix

#87 feat: Add setup-gh.sh script
  README.md
  src/setup-gh.sh
Labels: feat

#90 feat: Fix issue pull limits and add filter out done
  src/static_site_generator.py
  src/version2config.py
  src/version2query.py
  version2.py
Labels: feature, feat
